clear
clc
close all

rng(0)
data = round(10*rand(4, 3, 2)); % 4 groups per 3 columns
data_mixed = data-5;
data_neg = data-11;
data_sim = data_neg;
data_sim(:, :, 2) = data_sim(:, :, 1) + 1e-5;

figure
tiledlayout('flow')

nexttile
plotBarPlusDiff(data, ...
    'colors', eye(3), ...
    'groupLabels', {'group 1', 'group 2', 'group 3', 'group 4'}, ...
    'stackLabels', {'red', 'green', 'blue'}, ...
    'elementLabels', {' (darker)', ' (lighter)'}, ...
    'newFigure', false)
title('all data are non-negative')

nexttile
plotBarPlusDiff(data_mixed, ...
    'colors', eye(3), ...
    'groupLabels', {'group 1', 'group 2', 'group 3', 'group 4'}, ...
    'stackLabels', {'red', 'green', 'blue'}, ...
    'elementLabels', {' (darker)', ' (lighter)'}, ...
    'newFigure', false)
title('some data are negative')

nexttile
plotBarPlusDiff(data_neg, ...
    'colors', eye(3), ...
    'groupLabels', {'group 1', 'group 2', 'group 3', 'group 4'}, ...
    'stackLabels', {'red', 'green', 'blue'}, ...
    'elementLabels', {' (darker)', ' (lighter)'}, ...
    'newFigure', false)
title('all data are negative')

nexttile
plotBarPlusDiff(data_neg, ...
    'colors', eye(3), ...
    'groupLabels', {'group 1', 'group 2', 'group 3', 'group 4'}, ...
    'stackLabels', {'red', 'green', 'blue'}, ...
    'elementLabels', {' (darker)', ' (lighter)'}, ...
    'newFigure', false, ...
    'baseValue', -12)
title('all data are negative, different baseline')

nexttile
plotBarPlusDiff(data_sim, ...
    'colors', eye(3), ...
    'groupLabels', {'group 1', 'group 2', 'group 3', 'group 4'}, ...
    'stackLabels', {'red', 'green', 'blue'}, ...
    'elementLabels', {' (darker)', ' (lighter)'}, ...
    'newFigure', false, ...
    'baseValue', -12)
title('all data are negative and very similar, different baseline')